version: '3.0'

services:

  graph:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        from_tag: ${FROM_TAG:-3.4.12}
    image: informaticsmatters/neo4j:3.4
    container_name: neo4j
