version: '3.0'

services:

  graph:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        from_tag: ${IMAGE_TAG:-3.4.12}
    image: informaticsmatters/neo4j:3.4.12
    container_name: neo4j
